repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        args: [--config=./pyproject.toml]
        files: '\.py$'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        files: '\.py$'
    -   id: check-yaml
    -   id: end-of-file-fixer
        files: '\.py$'
    -   id: trailing-whitespace
        files: '\.py$'
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--settings-path=pyproject.toml]
        files: '\.py$'
